version: '3'

volumes:
  production_traefik: {}

services:
  streamlit:
    build: 
      context: .
      dockerfile: ./compose/streamlit/Dockerfile
    image: streamlit_production
    container_name: streamlit_app
    restart: always
    expose:
      - "8501"
    command: streamlit run src/app.py

  traefik:
    build:
      context: .
      dockerfile: ./compose/traefik/Dockerfile
    image: traefik_production
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"